<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>

    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <AssemblyName>CUButt</AssemblyName>
    <RootNamespace>CUButt</RootNamespace>

    <OutputPath>dist\</OutputPath>

    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <GameDir>D:\Games\Steam\steamapps\common\Casualties Unknown Demo</GameDir>
    <ManagedDir>$(GameDir)\CasualtiesUnknown_Data\Managed</ManagedDir>
    <BepInExCore>$(GameDir)\BepInEx\core</BepInExCore>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>$(BepInExCore)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

  <ItemGroup>

    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

  <ItemGroup>

    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(ManagedDir)\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

  <ItemGroup>
    <Reference Include="ButtplugManaged">
        <HintPath>lib\ButtplugManaged.dll</HintPath>
    </Reference>
    <Reference Include="WebSocketSharp">
        <HintPath>lib\websocket-sharp.dll</HintPath>
    </Reference>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>